chore: use pnpm to install release workflow

diff --git a/.github/workflows/publish-npm-beta.yml b/.github/workflows/publish-npm-beta.yml
--- a/.github/workflows/publish-npm-beta.yml
+++ b/.github/workflows/publish-npm-beta.yml
@@ -8,12 +8,6 @@ permissions:
 
 jobs:
   deploy-npm-beta:
-    - if: ${{ github.event.pull_request.merged != true && contains('["ghiscoding"]', github.actor) != true }}
-        name: Ensure current actor is allowed to run the workflow
-        run: |
-          echo "Error: Your GitHub username (${{ github.actor }}) is not on the allowed list of admins for this workflow"
-          exit 1
-
     runs-on: ubuntu-latest
     timeout-minutes: 30
     steps:
@@ -22,6 +16,12 @@ jobs:
         with:
           fetch-depth: 3
           token: ${{ secrets.GITHUB_TOKEN }}
+
+      - if: ${{ github.event.pull_request.merged != true && contains('["ghiscoding"]', github.actor) != true }}
+        name: Ensure current actor is allowed to run the workflow
+        run: |
+          echo "Error: Your GitHub username (${{ github.actor }}) is not on the allowed list of admins for this workflow"
+          exit 1
 
       - name: Set NodeJS
         uses: actions/setup-node@v4
